### ISSUE TITLE
Fix "sleep" link.

### ISSUE THREAD

**Issue by ConnorPhalen** [JetFuelCannotMeltSteelBeams/starter-routes#3]
### Expected behavior and actual behavior.

Bob Monkhouse's quote
### How to fix the problem.

Remapped to "zzz" method in "First" controller
### Requirements for fixing problem.

Wildcard Routing, leading to first/zzz

**Comment by PastaCode** [comment]
"sleep" image fixed.  A new routing rule was added that redirect /sleep to /first/zzz.
