### ISSUE TITLE
Fix "lock/em/up" link

### ISSUE THREAD

**Issue by ConnorPhalen** [JetFuelCannotMeltSteelBeams/starter-routes#4]
### Expected behavior and actual behavior.

Elaine Boosler's Quote
### How to fix the problem.

Remapped, using wildcards (lock / \* / *), i.e. the "shucks" method inside the "Welcome" controller
### Requirements for fixing problem.

Wildcard Routing, routing rule leasing to welcome/shucks

**Comment by PastaCode** [comment]
"lock/em/up" image fixed.  A new routing rule was added that redirect /lock/_/_ to /welcome/shucks.
