### ISSUE TITLE
Fix "show/3" link.

### ISSUE THREAD

**Issue by ConnorPhalen** [JetFuelCannotMeltSteelBeams/starter-routes#5]
### Expected behavior and actual behavior.

Mark Russel's quote
### How to fix the problem.

Remapped using Wildcard (show / digit)
### Requirements for fixing problem.

Wildcard Routing, Routing rule, leading to first/gimme/3), i.e. the "gimme" method inside the "First" controller, with that method defined to take a parameter

**Comment by PastaCode** [comment]
"show/3" image fixed. A new routing rule was added that redirect /show/(digit) to /first/(digit).
